on:
    workflow_call:
        inputs:
            dependencies:
                type: string
                required: false
                default: ''
            THEME_DIR:
                type: string
                required: false

env:
    dependencies: ${{ inputs.dependencies }}
# defaults:
#     run:
#         working-directory: ./wp-content/themes/demo-theme

jobs:
    build:
        name: Build + Deploy Assets
        if: always()
        needs: call-BackupSite
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - run: echo ${{ inputs.THEME_DIR }} '---';

            - run: echo ${{ inputs.dependencies }}
            - run: echo ${{env.dependencies}}
            - run: echo $dependencies
            - run: ls -la
