on:
    workflow_call:

jobs:
    DeployHost:
        name: Deploy Code to host
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - run: |
                  source=${{ github.ref }}

                  git checkout ${source#'refs/heads/'}

                  # git push $ORIGIN ${source#'refs/heads/'}
              name: Push repo changes
