name: Hotfix PR
run-name: ${{ github.repository }} - Hotfix PR - ${{ github.run_id }}

on:
    pull_request_target:
        # types:
        # - opened
        branches:
            - main

env:
    THEME_DIR: './wp-content/themes/demo-theme'
defaults:
    run:
        working-directory: ./wp-content/themes/demo-theme

jobs:
    call-HotfixPR:
        uses: ./.github/workflows/hotfixPR.template.yml
