name: Hotfix PR
# run-name: ${{ github.repository }} - Production - ${{ github.run_id }}

on:
    # [push]
    pull_request:
        branches:
            - main

env:
    THEME_DIR: './wp-content/themes/demo-theme'
defaults:
    run:
        working-directory: ./wp-content/themes/demo-theme

jobs:
    call-HotfixPR:
        uses: ./.github/workflows/hotfixPR.template.yml
