on:
    workflow_call:

jobs:
    job:
        name: Create PR to develop from hotfix or bugfix
        runs-on: ubuntu-latest
        if: ${{ ( (startsWith(github.head_ref, 'hotfix/') || startsWith(github.head_ref, 'bugfix/')) && startsWith(github.ref, 'refs/pull/') || true) }}

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - run: |
                  pr_info=$(gh pr view ${{github.event.number}} --json title,body)

                  pr_title=$(jq -r '.title' <<< "$pr_info")
                  pr_description=$(jq -r '.body' <<< "$pr_info")

                  msg="**[HOTFIX] - $pr_title**
                  $pr_description"

                  output=$(gh pr create --base develop --head ${{github.head_ref}} --title "Merge ${{github.head_ref}} to develop" --body "$msg")

              name: Create PR to develop from hotfix or bugfix
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
