on:
    workflow_call:

jobs:
    job:
        name: Create PR to develop from hotfix or bugfix
        runs-on: ubuntu-latest
        if: ${{ ( (startsWith(github.head_ref, 'hotfix/') || startsWith(github.head_ref, 'bugfix/')) && startsWith(github.ref, 'refs/pull/') || true) }}
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - run: |
                  echo 'yeah!'
                  # echo ${{github.ref}}
                  # echo ${{github.base_ref}}
                  # echo ${{github.head_ref}}


                  # echo ${{github.event.number}}

                  pr_info=$(gh pr view ${{github.event.number}} --json title,body)
                  echo $pr_info

                  pr_title = jq -r '.title' <<< "$pr_info"
                  echo $pr_title

                  pr_description = jq -r '.body' <<< "$pr_info"
                  echo $pr_description
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
