name: Production
run-name: ${{ github.repository }} - Production - ${{ github.run_number }}

on:
    [push]
    # push:
    #     branches:
    #         - main

env:
    THEME_DIR: 'wp-content/themes/demo-theme'
defaults:
    run:
        working-directory: ./wp-content/themes/demo-theme

jobs:
    call-BackupSite:
        uses: ./.github/workflows/backup.template.yml
    call-BuildAssets:
        uses: ./.github/workflows/build.template.yml
        with:
            THEME_DIR: 'wp-content/themes/demo-theme'
            dependencies: BackupSite
    # BuildAssets:
    #     name: Build + Deploy Assets
    #     runs-on: ubuntu-latest
    #     needs: [call-buildAssets]
    #     steps:
    #         - uses: actions/checkout@v4
    #           id: first_checkout
    #           with:
    #               fetch-depth: 0

    # - uses: ./.github/build
    #   with:
    #       dependencies: 'ssss'

    # - uses: actions/setup-node@v4
    #   with:
    #       node-version: 'latest'
    #       cache: 'npm'
    #       cache-dependency-path: ${{ env.THEME_DIR }}/package-lock.json
    # - run: npm ci
    #   name: npm install

    # - run: npm run build
    #   name: npm build

    # - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
