name: Production
run-name: ${{ github.repository }} - Production - ${{ github.run_attempt }}

on:
    [push]
    # push:
    #     branches:
    #         - main

env:
    THEME_DIR: './wp-content/themes/demo-theme'
defaults:
    run:
        working-directory: ./wp-content/themes/demo-theme

jobs:
    call-BackupSite:
        name: Create backup point
        uses: ./.github/workflows/backup.template.yml

    call-BuildAssets:
        uses: ./.github/workflows/build.template.yml
        needs: call-BackupSite
        with:
            THEME_DIR: './wp-content/themes/demo-theme'

    call-DeployHost:
        uses: ./.github/workflows/deploy.template.yml
        needs: call-BuildAssets
