name: Production
run-name: ${{ github.repository }} - Production - ${{ github.run_id }}

on:
    push:
        branches:
            - main

env:
    THEME_DIR: './wp-content/themes/demo-theme'
defaults:
    run:
        working-directory: ./wp-content/themes/demo-theme

jobs:
    call-BackupSite:
        uses: jessekahner/shared-actions/.github/workflows/backup.template.yml@main

    call-BuildAssets:
        uses: ./.github/workflows/build.template.yml
        needs: call-BackupSite
        with:
            THEME_DIR: './wp-content/themes/demo-theme'

    call-DeployHost:
        uses: jessekahner/shared-actions/.github/workflows/deploy.template.yml@main
        needs: call-BuildAssets
