name: Production
run-name: ${{ github.repository }} - Production - ${{ github.run_number }}

on:
    [push]
    # push:
    #     branches:
    #         - main

env:
    THEME_DIR: 'wp-content/themes/demo-theme'
defaults:
    run:
        working-directory: ./wp-content/themes/demo-theme

jobs:
    BuildAssets:
        name: Build + Deploy Assets
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: ./.github/workflows/build/

            - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
