on:
    workflow_call:

jobs:
    job:
        name: Create & merge PR from `production` to `staging`
        runs-on: ubuntu-latest
        # if: ${{ ( (startsWith(github.head_ref, 'hotfix/') || startsWith(github.head_ref, 'bugfix/')) && startsWith(github.ref, 'refs/pull/') || true) }}

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - run: |
                  output=$(gh pr create --base staging --head main --title "(automated) Merge main to staging" --body "This is an automated PR to update staging environment.")

                  echo ${{github.event}}
              name: Create & merge PR from `production` to `staging`
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
